using CfbFlairitorWeb.Services.Abstractions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CfbFlairitorWeb.Models;

namespace CfbFlairitorWeb.Services.Concretes
{
	public class StaticListFlairResolver : IFlairResolver
	{
		public IEnumerable<Flair> ResolveFlair()
		{
			return flairs;
		}

		private static IEnumerable<Flair> flairs = new List<Flair>()
		{
			new Flair("A", "(#f/a)"),
			new Flair("A", "(#f/alaskafairbanks-sheet7-row09-col02)"),
			new Flair("A", "(#f/allen-sheet7-row05-col01)"),
			new Flair("A", "(#f/auro-sheet6-row29-col01)"),
			new Flair("A", "(#f/asia-sheet6-row20-col01)"),
			new Flair("A", "(#f/uamn-sheet5-row20-col04)"),
			new Flair("A", "(#f/ipnsantotomas-sheet5-row16-col03)"),
			new Flair("A", "(#f/mountallison-sheet5-row08-col02)"),
			new Flair("A", "(#f/acadia-sheet5-row08-col01)"),
			new Flair("A", "(#f/amherst-sheet3-row18-col01)"),
			new Flair("A", "(#f/albright-sheet3-row13-col01)"),
			new Flair("A", "(#f/alma-sheet3-row12-col03)"),
			new Flair("A", "(#f/arizona)"),
			new Flair("A", "(#f/alcornstate)"),
			new Flair("A", "(#l/aac)"),
			new Flair("A", "(#f/stanselm-sheet2-row12-col09)"),

			new Flair("B", "(#f/b)"),
			new Flair("B", "(#f/bluefieldstate-sheet7-row07-col02)"),
			new Flair("B", "(#f/bradley-sheet7-row03-col01)"),
			new Flair("B", "(#f/bjut-sheet6-row24-col05)"),
			new Flair("B", "(#f/brunel-sheet5-row07-col07)"),
			new Flair("B", "(#f/bradford-sheet5-row06-col02)"),
			new Flair("B", "(#f/derby-sheet5-row03-col03)"),
			new Flair("B", "(#f/longbeachcity-sheet4-row15-col09)"),
			new Flair("B", "(#f/birminghamsouthern-sheet3-row24-col02)"),
			new Flair("B", "(#f/benedictine-sheet3-row15-col02)"),
			new Flair("B", "(#f/bentley-sheet2-row12-col03)"),
			new Flair("B", "(#f/belhaven-sheet3-row02-col01)" ),

			new Flair("C", "(#f/c)"),
			new Flair("C", "(#f/collegecharleston-sheet7-row04-col04)"),
			new Flair("C", "(#f/centenary-sheet7-row04-col03)"),
			new Flair("C", "(#f/beauceappalaches-sheet5-row14-col01)"),
			new Flair("C", "(#f/cabrillo-sheet4-row12-col01)"),
			new Flair("C", "(#f/carrollmt-sheet4-row03-col01)"),
			new Flair("C", "(#f/chapman-sheet3-row26-col02)"),
			new Flair("C", "(#f/centre-sheet3-row24-col03)"),
			new Flair("C", "(#f/chicago-sheet3-row24-col04)"),
			new Flair("C", "(#f/concordiamoorhead-sheet3-row11-col04)"),
			new Flair("C", "(#f/sunycortland-sheet3-row06-col04)"),
			new Flair("C", "(#f/cincinnati)"),
			new Flair("C", "(#f/charlotte)"),
			new Flair("C", "(#f/centralmichigan)"),
			new Flair("C", "(#f/colgate)"),
			new Flair("C", "(#f/chattanooga)"),
			new Flair("C", "(#f/chowan-sheet2-row02-col02)"),
			new Flair("C", "(#f/carthage-sheet3-row03-col02)"),
			new Flair("C", "(#f/carrollwi-sheet3-row03-col03)" ),

			new Flair("D", "(#f/d)"),
			new Flair("D", "(#f/dokkyo-sheet6-row21-col12)"),
			new Flair("D", "(#f/osakakyoiku-sheet6-row11-col07)"),
			new Flair("D", "(#f/troisrivieres-sheet5-row14-col08)"),
			new Flair("D", "(#f/durham-sheet5-row03-col04)"),
			new Flair("D", "(#f/dean-sheet3-row05-col05)"),
			new Flair("D", "(#f/denison-sheet3-row16-col02)"),
			new Flair("D", "(#f/dickinson-sheet3-row04-col01)"),
			new Flair("D", "(#f/duke)"),
			new Flair("D", "(#f/dartmouth)"),
			new Flair("D", "(#f/dayton)"),
			new Flair("D", "(#l/dallas)"),
			new Flair("D", "(#f/ohiodominican-sheet2-row05-col11)" ),

			new Flair("E", "(#f/e)"),
			new Flair("E", "(#f/shawinigan-sheet5-row15-col09)"),
			new Flair("E", "(#f/easternconnecticutstate-sheet4-row30-col04)"),
			new Flair("E", "(#f/wisconsineauclaire-sheet3-row29-col01)"),
			new Flair("E", "(#f/easternmichigan)"),
			new Flair("E", "(#f/elon)"),
			new Flair("E", "(#f/easttennesseestate)"),
			new Flair("E", "(#f/emporiastate-sheet2-row11-col03)" ),

			new Flair("F", "(#f/f)"),
			new Flair("F", "(#f/csufullerton-sheet7-row02-col03)" ),

			new Flair("G", "(#f/g)"),
			new Flair("G", "(#f/gakushuin-sheet6-row12-col03)"),
			new Flair("G", "(#f/kyoto-sheet6-row02-col01)"),
			new Flair("G", "(#f/jonquiere-sheet5-row15-col05)"),
			new Flair("G", "(#f/gattacaflorida-sheet4-row25-col01)"),
			new Flair("G", "(#f/gardencitycc-sheet4-row17-col05)"),
			new Flair("G", "(#f/saddleback-sheet4-row15-col16)"),
			new Flair("G", "(#f/grovecity-sheet3-row23-col05)"),
			new Flair("G", "(#f/guilford-sheet3-row22-col04)"),
			new Flair("G", "(#f/gettysburg-sheet3-row04-col03)"),
			new Flair("G", "(#f/georgetown)"),
			new Flair("G", "(#f/gramblingstate)"),
			new Flair("G", "(#f/glenvillestate-sheet2-row10-col04)" ),

			new Flair("H", "(#f/h)"),
			new Flair("H", "(#f/huntington-sheet7-row11-col05)"),
			new Flair("H", "(#f/edogawa-sheet6-row21-col11)"),
			new Flair("H", "(#f/hokkaido-sheet6-row06-col03)"),
			new Flair("H", "(#f/holland-sheet5-row12-col02)"),
			new Flair("H", "(#f/hartford-sheet4-row31-col02)"),
			new Flair("H", "(#f/hastings-sheet4-row04-col06)"),
			new Flair("H", "(#f/huntingdon-sheet3-row28-col04)"),
			new Flair("H", "(#f/hobart-sheet3-row09-col01)"),
			new Flair("H", "(#f/harvard)"),
			new Flair("H", "(#f/hendersonstate-sheet2-row04-col05)"),
			new Flair("H", "(#f/husson-sheet3-row05-col07)" ),

			new Flair("I", "(#f/i)"),
			new Flair("I", "(#f/kogakuin-sheet6-row21-col04)"),
			new Flair("I", "(#f/illinois)"),
			new Flair("I", "(#f/indiana2-sheet1-row04-col15)"),
			new Flair("I", "(#f/indianapolis-sheet2-row06-col01)" ),

			new Flair("J", "(#f/j)" ),

			new Flair("K", "(#f/k)"),
			new Flair("K", "(#f/kanagawatech-sheet6-row21-col14)"),
			new Flair("K", "(#f/kurume-sheet6-row08-col01)"),
			new Flair("K", "(#f/knox-sheet3-row14-col05)"),
			new Flair("K", "(#f/kalamazoo-sheet3-row12-col05)" ),

			new Flair("L", "(#f/l)"),
			new Flair("L", "(#f/loyolachicago-sheet7-row04-col09)"),
			new Flair("L", "(#f/wisconsinlacrosse-sheet3-row29-col02)"),
			new Flair("L", "(#f/lafayette)"),
			new Flair("L", "(#f/lehigh)"),
			new Flair("L", "(#f/lycoming-sheet3-row13-col07)" ),

			new Flair("M", "(#f/m)"),
			new Flair("M", "(#f/midplainscc-sheet7-row13-col24)"),
			new Flair("M", "(#f/collegemarin-sheet7-row13-col06)"),
			new Flair("M", "(#f/menlo-sheet7-row05-col09)"),
			new Flair("M", "(#f/manhattan-sheet7-row04-col11)"),
			new Flair("M", "(#f/meisei-sheet6-row21-col07)"),
			new Flair("M", "(#f/mie-sheet6-row17-col01)"),
			new Flair("M", "(#f/murorantech-sheet6-row14-col03)"),
			new Flair("M", "(#f/mcgill-sheet5-row11-col04)"),
			new Flair("M", "(#f/mcmaster-sheet5-row10-col03)"),
			new Flair("M", "(#f/saintmarys-sheet5-row08-col04)"),
			new Flair("M", "(#f/mansfield-sheet4-row32-col04)"),
			new Flair("M", "(#f/mayvillestate-sheet4-row09-col04)"),
			new Flair("M", "(#f/millsaps-sheet3-row24-col06)"),
			new Flair("M", "(#f/muhlenberg-sheet3-row04-col08)"),
			new Flair("M", "(#f/michigan)"),
			new Flair("M", "(#f/minnesota)"),
			new Flair("M", "(#f/minnesota)"),
			new Flair("M", "(#f/minnesota)"),
			new Flair("M", "(#f/minnesota)"),
			new Flair("M", "(#f/minnesota)"),
			new Flair("M", "(#f/minnesota)"),
			new Flair("M", "(#f/minnesota)"),
			new Flair("M", "(#f/minnesota)"),
			new Flair("M", "(#f/minnesota)"),
			new Flair("M", "(#f/minnesota)"),
			new Flair("M", "(#f/minnesota)"),
			new Flair("M", "(#f/michigan2-sheet1-row04-col16)"),
			new Flair("M", "(#f/murraystate)"),
			new Flair("M", "(#f/mercyhurst-sheet2-row13-col11)"),
			new Flair("M", "(#f/millikin-sheet3-row03-col06)" ),

			new Flair("N", "(#f/n)"),
			new Flair("N", "(#f/northeastern-sheet7-row02-col11)"),
			new Flair("N", "(#f/northampton-sheet5-row06-col17)"),
			new Flair("N", "(#f/northumbria-sheet5-row04-col08)"),
			new Flair("N", "(#f/northwestmississippicc-sheet4-row19-col12)"),
			new Flair("N", "(#f/northlandctc-sheet4-row18-col09)"),
			new Flair("N", "(#f/nebraska)"),
			new Flair("N", "(#f/northwestern)"),
			new Flair("N", "(#f/navy)"),
			new Flair("N", "(#f/nicholls)"),
			new Flair("N", "(#f/newberry-sheet2-row17-col07)" ),

			new Flair("O", "(#f/o)"),
			new Flair("O", "(#f/sise-sheet6-row25-col08)"),
			new Flair("O", "(#f/otemongakuin-sheet6-row11-col12)"),
			new Flair("O", "(#f/amu-sheet5-row30-col01)"),
			new Flair("O", "(#f/oxford-sheet5-row05-col07)"),
			new Flair("O", "(#f/ohiostate)"),
			new Flair("O", "(#f/ohiostate3-sheet1-row04-col19)"),
			new Flair("O", "(#f/oregon)" ),

			new Flair("P", "(#f/p)"),
			new Flair("P", "(#f/portland-sheet7-row04-col12)"),
			new Flair("P", "(#f/pepperdine-sheet7-row03-col14)"),
			new Flair("P", "(#f/kyushu-sheet6-row08-col02)"),
			new Flair("P", "(#f/uqtr-sheet5-row11-col07)"),
			new Flair("P", "(#f/edinburgh-sheet5-row06-col07)"),
			new Flair("P", "(#f/purdue)"),
			new Flair("P", "(#f/pennsylvania)"),
			new Flair("P", "(#f/princeton)"),
			new Flair("P", "(#l/pioneer)"),
			new Flair("P", "(#f/liupost-sheet2-row12-col04)" ),

			new Flair("Q", "(#f/q)"),
			new Flair("Q", "(#f/queens-sheet5-row10-col05)"),
			new Flair("Q", "(#f/quincy-sheet2-row06-col05)" ),

			new Flair("R", "(#f/r)"),
			new Flair("R", "(#f/melbourne-sheet5-row21-col03)"),
			new Flair("R", "(#f/regina-sheet5-row09-col04)"),
			new Flair("R", "(#f/rockford-sheet3-row15-col06)"),
			new Flair("R", "(#f/ripon-sheet3-row14-col10)"),
			new Flair("R", "(#f/rosehulman-sheet3-row07-col09)"),
			new Flair("R", "(#f/rutgers)"),
			new Flair("R", "(#f/rice)" ),

			new Flair("S", "(#f/s)"),
			new Flair("S", "(#f/saleminternational-sheet7-row07-col16)"),
			new Flair("S", "(#f/swarthmore-sheet7-row06-col17)"),
			new Flair("S", "(#f/bogazici-sheet6-row33-col05)"),
			new Flair("S", "(#f/beijingsport-sheet6-row24-col03)"),
			new Flair("S", "(#f/kanda-sheet6-row21-col15)"),
			new Flair("S", "(#f/shibaura-sheet6-row20-col20)"),
			new Flair("S", "(#f/setsunan-sheet6-row18-col15)"),
			new Flair("S", "(#f/parisrenedescartes-sheet5-row30-col15)"),
			new Flair("S", "(#f/inptoulouse-sheet5-row30-col07)"),
			new Flair("S", "(#f/sherbrooke-sheet5-row11-col06)"),
			new Flair("S", "(#f/collegesequoias-sheet4-row13-col05)"),
			new Flair("S", "(#f/wisconsinstout-sheet3-row29-col07)"),
			new Flair("S", "(#f/wisconsinstout-sheet3-row29-col07)"),
			new Flair("S", "(#f/wisconsinstout-sheet3-row29-col07)"),
			new Flair("S", "(#f/wisconsinstout-sheet3-row29-col07)"),
			new Flair("S", "(#f/wisconsinstout-sheet3-row29-col07)"),
			new Flair("S", "(#f/wisconsinstout-sheet3-row29-col07)"),
			new Flair("S", "(#f/sewanee-sheet3-row24-col08)"),
			//new Flair("S", "(#f/susquehanna-sheet3-row04-col09)"),
			new Flair("S", "(#f/syracuse)"),
			new Flair("S", "(#f/stanford)"),
			new Flair("S", "(#f/shepherd-sheet2-row10-col06)"),
			new Flair("S", "(#f/stonehill-sheet2-row12-col10)" ),
			new Flair("S", "(#f/shorelinecc-sheet7-row14-col17)" ),

			new Flair("T", "(#f/t)"),
			new Flair("T", "(#f/transylvania-sheet7-row11-col19)"),
			new Flair("T", "(#f/teikyoheisei-sheet6-row21-col05)"),
			new Flair("T", "(#f/teikyo-sheet6-row04-col03)"),
			new Flair("T", "(#f/puebla-sheet5-row18-col03)"),
			new Flair("T", "(#f/uag-sheet5-row17-col06)"),
			new Flair("T", "(#f/thetford-sheet5-row15-col12)"),
			new Flair("T", "(#f/lanaudiere-sheet5-row14-col05)"),
			new Flair("T", "(#f/toronto-sheet5-row10-col06)"),
			new Flair("T", "(#f/texastech)"),
			new Flair("T", "(#f/trinitytx-sheet3-row25-col04)"),
			new Flair("T", "(#f/temple)"),
			new Flair("T", "(#f/trine-sheet3-row12-col07)"),
			new Flair("T", "(#f/tulane)"),
			new Flair("T", "(#f/troy)"),
			new Flair("T", "(#f/tarletonstate-sheet2-row09-col05)" ),
			new Flair("T", "(#f/texarkanacollege-sheet7-row14-col24)"),

			new Flair("U", "(#f/u)"),
			new Flair("U", "(#f/portsmouth-sheet5-row05-col08)"),
			new Flair("U", "(#f/staffordshire-sheet5-row04-col11)"),
			new Flair("U", "(#f/union-sheet3-row09-col07)"),
			new Flair("U", "(#f/miami)"),
			new Flair("U", "(#f/usf)"),
			new Flair("U", "(#f/urbana-sheet2-row10-col07)"),

			new Flair("V", "(#f/v)"),
			new Flair("V", "(#f/laurentian-sheet7-row16-col03)"),
			new Flair("V", "(#f/drummondville-sheet5-row14-col03)"),
			new Flair("V", "(#f/vermillion-sheet4-row18-col12)"),
			new Flair("V", "(#f/virginia)"),
			new Flair("V", "(#f/villanova)"),
			new Flair("V", "(#f/valleycup-sheetl-row20-col10)"),
			new Flair("V", "(#f/virginiaunion-sheet2-row02-col11)"),
			new Flair("V", "(#f/valdostastate-sheet2-row08-col07)" ),

			new Flair("W", "(#f/w)"),
			new Flair("W", "(#f/wakayama-sheet6-row18-col08)"),
			new Flair("W", "(#f/yokkaichi-sheet6-row17-col06)"),
			new Flair("W", "(#f/waseda-sheet6-row03-col05)"),
			new Flair("W", "(#f/kindai-sheet6-row11-col11)"),
			new Flair("W", "(#f/monash-sheet5-row21-col04)"),
			new Flair("W", "(#f/webberinternational-sheet4-row10-col06)"),
			new Flair("W", "(#f/wesleyan-sheet3-row18-col09)"),
			new Flair("W", "(#f/wooster-sheet3-row16-col10)"),
			new Flair("W", "(#f/wilkes-sheet3-row13-col10)"),
			new Flair("W", "(#f/wisconsin)"),
			new Flair("W", "(#f/wisconsin)"),
			new Flair("W", "(#f/wisconsin)"),
			new Flair("W", "(#f/wisconsin)"),
			new Flair("W", "(#f/wisconsin)"),
			new Flair("W", "(#f/wisconsin)"),
			new Flair("W", "(#f/wisconsin)"),
			new Flair("W", "(#f/washington)"),
			new Flair("W", "(#f/waynestatemi-sheet2-row05-col15)"),
			new Flair("W", "(#f/washburn-sheet2-row11-col12)" ),

			new Flair("X", "(#f/x)"),
			new Flair("X", "(#f/xavier-sheet7-row03-col24)"),
			new Flair("X", "(#f/standrews-sheet6-row11-col09)"),
			new Flair("X", "(#f/stfrancisxavier-sheet5-row08-col03)" ),

			new Flair("Y", "(#f/y)"),
			new Flair("Y", "(#f/byu)"),
			new Flair("Y", "(#f/yale)" ),

			new Flair("Z", "(#f/z)"),
			new Flair("Z", "(#f/akron)" ),

		};
	}
}
